#export LD_ASSUME_KERNEL=2.4.1
export CDSDIR=${CADENCE_PATH}/IC5141

export CDS_ROOT=${CADENCE_PATH}/IC5141

export CDSROOT=${CADENCE_PATH}/IC5141

export CDS_INST_DIR=${CADENCE_PATH}/IC5141

export CDSHOME=${CADENCE_PATH}/IC5141

export CDS_HOME=${CADENCE_PATH}/IC5141

export CDS_INSTALL_DIR=${CADENCE_PATH}/IC5141/tools/dfII

PATH=$PATH:${CDSDIR}:${CDS_ROOT}/tools/bin:${CDS_ROOT}/tools/spectre/bin
PATH=$PATH:${CDS_INSTALL_DIR}/bin
