;#########################################################################
;#                  Virtuoso Technology File                             #
;#########################################################################
;#
;#=======================================================================
;#  @Process SMIC 0.18um Logical/SRAM/Mask ROM/Mix-Mode/HVCM/LMOS process
;#=======================================================================
;# @File Comment
;#    with @(#)$CDS: icfb.exe version 5.0.0 09/26/2003 18:23 (cds12107) $
;#
;# $RCSfile: SmicVTTF_LO_SRAM_MR_MM_HV_LC_018.tf,v $
;# $Date: 2005/10/06 05:47:05 $
;#
;# Author: Smic DSD
;#
;# Revision History:
;#     Rev     Date         Who                   What
;#   -----   ---------   ---------      --------------------------------
;#    1.1   2003/04/03   Wendy Sui              Initial
;#    1.2   2003/04/07   Micky Yu               Add ALPA
;#    1.3   2004/03/08   Jacky Chang     Add some CAD and Mask lalyers
;#    1.4   2004/03/09   Jacky Chang     Add RFDEV, RFMOSD, JVARDUM layer
;#    1.5   2004/03/29   Jacky Chang     Add ONO, TG, NLHT, PLHT layer
;#    1.6   2004/04/28   Jacky Chang     Add PFL and viaLayers definition
;#    1.7   2004/07/09   Jacky Chang     Add SDOP, PWHT, NWHT,, NDRF, PDRF
;#                                           SURNW and STIDMY layers
;#    1.8   2004/07/14   Jacky Chang     Modify the PDRF stream layer number
;#    1.9   2004/08/06   Shelly Liu      Add L0, 0M, RGM, HT and NEGR layers
;#    2.0   2004/09/07   Shelly Liu      Change the grid resolution.
;#    2.1   2004/09/10   Shelly Liu      Add dummy layer for AA and GT.
;#    2.2   2004/11/18   Shelly Liu      Add dummy layer for job view.
;#    2.3   2004/12/20   shelly Liu      Modify some layer names.
;#    2.4   2005/09/15   longle shi      Add some layers
;#
;#***********************************************************************

;DISCLAIMER

;SMIC hereby provides the quality information to you but makes no claims,
;promises or guarantees about the accuracy, completeness, or adequacy of
;the information herein. The information contained herein is provided on
;an "AS IS" basis without any warranty, and SMIC assumes no obligation to
;provide support of any kind or otherwise maintain the information.
;SMIC disclaims any representation that the information does not infringe
;any intellectual property rights or proprietary rights of any third parties.
;SMIC makes no other warranty, whether express, implied or statutory as to
;any matter whatsoever, including but not limited to the accuracy or sufficiency
;of any information or the merchantability and fitness for a particular purpose.
;Neither SMIC nor any of its representatives shall be liable for any cause of
;action incurred to connect to this service.
;STATEMENT OF USE AND CONFIDENTIALITY
;The following/attached material contains confidential and proprietary information
;of SMIC. This material is based upon information which SMIC considers reliable,
;but SMIC neither represents nor warrants that such information is accurate or
;complete, and it must not be relied upon as such.  This information was prepared
;for informational purposes and is for the use by SMIC's customer only.  SMIC
;reserves the right to make changes in the information at any time without notice.
;No part of this information may be reproduced, transmitted, transcribed, stored
;in a retrieval system, or translated into any human or computer language, in any
;form or by any means, electronic, mechanical, magnetic, optical, chemical, manual,
;or otherwise, without the prior written consent of SMIC.  Any unauthorized use or
;disclosure of this material is strictly prohibited and may be unlawful. By accepting
;this material, the receiving party shall be deemed to have acknowledged, accepted,
;and agreed to be bound by the foregoing limitations and restrictions. Thank you.

;###########################################################################
;########
;###########################################################################
;########


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
 ;System-Reserved Purposes:
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( drawing                   252        drw          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( DUMAA                     0          DUMAA        )
  ( SURNW                     1          SURNW        )
  ( STIDMY                    2          STIDMY       )
  ( SDOP                      3          SDOP         )
  ( ONO                       4          ONO          )
  ( M1DUM                     5          M1DUM        )
  ( RODUMMY                   6          RODUMMY      )
  ( AMO                       7          AMO          )
  ( CO                        8          CO           )
  ( KV                        9          KV           )
  ( AA                        10         AA           )
  ( AR                        11         AR           )
  ( NPAA                      12         NPAA         )
  ( PPAA                      13         PPAA         )
  ( NW                        14         NW           )
  ( TP                        15         TP           )
  ( PC                        16         PC           )
  ( DP                        17         DP           )
  ( CL                        18         CL           )
  ( DNW                       19         DNW          )
  ( PW                        20         PW           )
  ( NC                        21         NC           )
  ( CPT                       22         CPT          )
  ( BNP                       23         BNP          )
  ( TN                        24         TN           )
  ( CODE                      25         CODE         )
  ( LOGO                      26         LOGO         )
  ( M1SLOT                    27         M1SLOT       )
  ( BC                        28         BC           )
  ( DG                        29         DG           )
  ( GT                        30         GT           )
  ( P2                        31         P2           )
  ( P3                        32         P3           )
  ( P4                        33         P4           )
  ( HR                        34         HR           )
  ( NLL                       35         NLL          )
  ( NLH                       36         NLH          )
  ( PLH                       37         PLH          )
  ( PLL                       38         PLL          )
  ( HRP                       39         HRP          )
  ( SN                        40         SN           )
  ( ESD1                      41         ESD1         )
  ( ESD2                      42         ESD2         )
  ( SP                        43         SP           )
  ( MVP                       44         MVP          )
  ( MVN                       45         MVN          )
  ( VTPH                      46         VTPH         )
  ( VTNH                      47         VTNH         )
  ( SAB                       48         SAB          )
  ( IDT                       49         IDT          )
  ( CT                        50         CT           )
  ( CM                        51         CM           )
  ( M2DUM                     52         M2DUM        )
  ( DDN                       53         DDN          )
  ( HVBN                      54         HVBN         )
  ( NDDD                      55         NDDD         )
  ( DDP                       56         DDP          )
  ( M2SLOT                    57         M2SLOT       )
  ( MIM                       58         MIM          )
  ( M0                        59         M0           )
  ( INST                      60         INST         )
  ( M1                        61         M1           )
  ( M2                        62         M2           )
  ( M3                        63         M3           )
  ( M4                        64         M4           )
  ( M5                        65         M5           )
  ( M6                        66         M6           )
  ( M7                        67         M7           )
  ( M8                        68         M8           )
  ( PFL                       69         PFL          )
  ( V1                        70         V1           )
  ( V2                        71         V2           )
  ( V3                        72         V3           )
  ( V4                        73         V4           )
  ( V5                        74         V5           )
  ( V6                        75         V6           )
  ( V7                        76         V7           )
  ( NDRF                      77         NDRF         )
  ( M3DUM                     78         M3DUM        )
  ( PIPR                      79         PIPR         )
  ( PA                        80         PA           )
  ( FUSE                      81         FUSE         )
  ( PI                        82         PI           )
  ( ALPA                      83         ALPA         )
  ( M3SLOT                    84         M3SLOT       )
  ( NN                        85         NN           )
  ( VSIA                      86         VSIA         )
  ( TTXT                      87         TTXT         )
  ( BTXT                      88         BTXT         )
  ( CTXT                      89         CTXT         )
  ( DUMBM                     90         DUMBM        )
  ( DUMBA                     91         DUMBA        )
  ( DUMBP                     92         DUMBP        )
  ( VARMOS                   93         VARMOS      )
  ( VARJUN                  94         VARJUN     )
  ( RESNW                    95         RESNW       )
  ( RESP1                    96         RESP1       )
  ( RESAA                    97         RESAA       )
  ( SUBD                      98         SUBD         )
  ( PDRF                      99         PDRF         )
  ( OPCBA                     100        OPCBA        )
  ( OPCBP                     101        OPCBP        )
  ( OPCBM                     102        OPCBM        )
  ( M3DUB                     103        M3DUB        )
  ( M4DUB                     104        M4DUB        )
  ( PWH                       105        PWH          )
  ( NWH                       106        NWH          )
  ( PPCI                      107        PPCI         )
  ( NPCI                      108        NPCI         )
  ( M5DUB                     109        M5DUB        )
  ( M6DUB                     110        M6DUB        )
  ( M7DUB                     111        M7DUB        )
  ( M8DUB                     112        M8DUB        )
  ( PIP                       113        PIP          )
  ( M1SLOTB                   114        M1SLOTB      )
  ( M2SLOTB                   115        M2SLOTB      )
  ( M4DUM                     116        M4DUM        )
  ( M7SLOTB                   117        M7SLOTB      )
  ( M8SLOTB                   118        M8SLOTB      )
  ( NLHT                      119        NLHT         )
  ( PLHT                      120        PLHT         )
  ( PWHT                      121        PWHT         )
  ( NWHT                      122        NWHT         )
  ( L0                        123        L0           )
  ( ESD5V                     124        ESD5V        )
  ( TG                        125        TG           )
  ( M4SLOT                    126        M4SLOT       )
  ( BORDER                    127        BORDER       )
  ( M5DUM                     128        M5DUM        )
  ( M5SLOT                    129        M5SLOT       )
  ( M6SLOT                    130        M6SLOT       )
  ( HTNWL                     131        htnwl        )
  ( EXCLU                     132        EXCLU        )
  ( ESDIO1                    133        ESDIO1       )
  ( DMPNP                     134        DMPNP        )
  ( PDC                       135        PDC          )
  ( PWL                       136        PWL          )
  ( CAPBP                     137        CAPBP        )
  ( DSTR                      138        DSTR         )
  ( DCTY                      139        DCTY         )
  ( SBT                       140        SBT          )
  ( M1TXT                     141        M1TXT        )
  ( M2TXT                     142        M2TXT        )
  ( M3TXT                     143        M3TXT        )
  ( M4TXT                     144        M4TXT        )
  ( M5TXT                     145        M5TXT        )
  ( M6TXT                     146        M6TXT        )
  ( M7TXT                     147        M7TXT        )
  ( M8TXT                     148        M8TXT        )
  ( "0M"                      149        "0M"         )
  ( M7DUM                     150        M7DUM        )
  ( M1B                       151        M1B          )
  ( M2B                       152        M2B          )
  ( M3B                       153        M3B          )
  ( M4B                       154        M4B          )
  ( M5B                       155        M5B          )
  ( M6B                       156        M6B          )
  ( M7B                       157        M7B          )
  ( M8B                       158        M8B          )
  ( RGM                       159        RGM          )
  ( M7SLOT                    160        M7SLOT       )
  ( SUBTXT                    161        SUBTXT       )
  ( WELTXT                    162        WELTXT       )
  ( DIFTXT                    163        DIFTXT       )
  ( POLYTXT                   164        POLYTXT      )
  ( HT                        165        HT           )
  ( NEGR                      166        NEGR         )
  ( DUMGT                     167        DUMGT        )
  ( JVDUM                     168        JVDUM        )
  ( M6DUM                     169        M6DUM        )
  ( M8DUM                     170        M8DUM        )
  ( M1R                       171        M1R          )
  ( M2R                       172        M2R          )
  ( M3R                       173        M3R          )
  ( M4R                       174        M4R          )
  ( M5R                       175        M5R          )
  ( M6R                       176        M6R          )
  ( M7R                       177        M7R          )
  ( M8R                       178        M8R          )
  ( POWRING                   179        POWRING      )
  ( NODMF                     180        NODMF        )
  ( HRPDMY                    181        HRPDMY       )
  ( M8SLOT                    182        M8SLOT       )
  ( M1DUB                     183        M1DUB        )
  ( M2DUB                     184        M2DUB        )
  ( M3SLOTB                   185        M3SLOTB      )
  ( M4SLOTB                   186        M4SLOTB      )
  ( M5SLOTB                   187        M5SLOTB      )
  ( M6SLOTB                   188        M6SLOTB      )
  ( MIMDMY                    189        MIMDMY       )
  ( INDMY                     190        INDMY        )
  ( RFDEV                     191        RFDEV        )
  ( RFMOSD                    192        RFMOSD       )
  ( JVARDUM                   193        JVARDUM      )
  ( ESDIO2                    194        ESDIO2       )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( "0M"                      drawing    )
  ( RGM                       drawing    )
  ( HT                        drawing    )
  ( NEGR                      drawing    )
  ( L0                        drawing    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( AA                        drawing    )
  ( DUMAA                     drawing    )
  ( NPAA                      drawing    )
  ( PPAA                      drawing    )
  ( NW                        drawing    )
  ( GT                        drawing    )
  ( DUMGT                     drawing    )
  ( DG                        drawing    )
  ( HRP                       drawing    )
  ( SN                        drawing    )
  ( SP                        drawing    )
  ( SAB                       drawing    )
  ( VSIA                      drawing    )
  ( CT                        drawing    )
  ( M1                        drawing    )
  ( M2                        drawing    )
  ( M3                        drawing    )
  ( M4                        drawing    )
  ( M5                        drawing    )
  ( M6                        drawing    )
  ( M7                        drawing    )
  ( M8                        drawing    )
  ( V1                        drawing    )
  ( V2                        drawing    )
  ( V3                        drawing    )
  ( V4                        drawing    )
  ( V5                        drawing    )
  ( V6                        drawing    )
  ( V7                        drawing    )
  ( PA                        drawing    )
  ( M1TXT                     drawing    )
  ( M2TXT                     drawing    )
  ( M3TXT                     drawing    )
  ( M4TXT                     drawing    )
  ( M5TXT                     drawing    )
  ( M6TXT                     drawing    )
  ( M7TXT                     drawing    )
  ( M8TXT                     drawing    )
  ( NN                        drawing    )
  ( RESNW                    drawing    )
  ( RESP1                    drawing    )
  ( RESAA                    drawing    )
  ( SUBD                      drawing    )
  ( HTNWL                     drawing    )
  ( EXCLU                     drawing    )
  ( ESDIO1                    drawing    )
  ( POWRING                   drawing    )
  ( ESDIO2                    drawing    )
  ( DMPNP                     drawing    )
  ( CAPBP                     drawing    )
  ( DSTR                      drawing    )
  ( SURNW                     drawing    )
  ( AMO                       drawing    )
  ( CO                        drawing    )
  ( BORDER                    drawing    )
  ( KV                        drawing    )
  ( AR                        drawing    )
  ( TP                        drawing    )
  ( PC                        drawing    )
  ( DP                        drawing    )
  ( CL                        drawing    )
  ( DNW                       drawing    )
  ( PW                        drawing    )
  ( NC                        drawing    )
  ( CPT                       drawing    )
  ( BNP                       drawing    )
  ( TN                        drawing    )
  ( CODE                      drawing    )
  ( LOGO                      drawing    )
  ( ONO                       drawing    )
  ( BC                        drawing    )
  ( P2                        drawing    )
  ( P3                        drawing    )
  ( P4                        drawing    )
  ( HR                        drawing    )
  ( NLL                       drawing    )
  ( NLH                       drawing    )
  ( PLH                       drawing    )
  ( PLL                       drawing    )
  ( ESD1                      drawing    )
  ( ESD2                      drawing    )
  ( MVP                       drawing    )
  ( MVN                       drawing    )
  ( VTPH                      drawing    )
  ( VTNH                      drawing    )
  ( IDT                       drawing    )
  ( CM                        drawing    )
  ( DDN                       drawing    )
  ( HVBN                      drawing    )
  ( NDDD                      drawing    )
  ( DDP                       drawing    )
  ( MIM                       drawing    )
  ( M0                        drawing    )
  ( INST                      drawing    )
  ( M1DUM                     drawing    )
  ( M2DUM                     drawing    )
  ( M3DUM                     drawing    )
  ( M4DUM                     drawing    )
  ( M5DUM                     drawing    )
  ( M6DUM                     drawing    )
  ( M7DUM                     drawing    )
  ( M8DUM                     drawing    )
  ( M1SLOT                    drawing    )
  ( M2SLOT                    drawing    )
  ( M3SLOT                    drawing    )
  ( M4SLOT                    drawing    )
  ( M5SLOT                    drawing    )
  ( M6SLOT                    drawing    )
  ( M7SLOT                    drawing    )
  ( M8SLOT                    drawing    )
  ( PIPR                      drawing    )
  ( FUSE                      drawing    )
  ( PI                        drawing    )
  ( ALPA                      drawing    )
  ( TTXT                      drawing    )
  ( BTXT                      drawing    )
  ( CTXT                      drawing    )
  ( DUMBM                     drawing    )
  ( DUMBA                     drawing    )
  ( DUMBP                     drawing    )
  ( VARMOS                   drawing    )
  ( VARJUN                  drawing    )
  ( PFL                       drawing    )
  ( SDOP                      drawing    )
  ( OPCBA                     drawing    )
  ( OPCBP                     drawing    )
  ( OPCBM                     drawing    )
  ( NDRF                      drawing    )
  ( PDRF                      drawing    )
  ( PPCI                      drawing    )
  ( NPCI                      drawing    )
  ( PWHT                      drawing    )
  ( NWHT                      drawing    )
  ( PIP                       drawing    )
  ( NLHT                      drawing    )
  ( PLHT                      drawing    )
  ( ESD5V                     drawing    )
  ( TG                        drawing    )
  ( PDC                       drawing    )
  ( PWL                       drawing    )
  ( DCTY                      drawing    )
  ( SBT                       drawing    )
  ( SUBTXT                    drawing    )
  ( WELTXT                    drawing    )
  ( DIFTXT                    drawing    )
  ( POLYTXT                   drawing    )
  ( M1B                       drawing    )
  ( M2B                       drawing    )
  ( M3B                       drawing    )
  ( M4B                       drawing    )
  ( M5B                       drawing    )
  ( M6B                       drawing    )
  ( M7B                       drawing    )
  ( M8B                       drawing    )
  ( M1DUB                     drawing    )
  ( M2DUB                     drawing    )
  ( M3DUB                     drawing    )
  ( M4DUB                     drawing    )
  ( M5DUB                     drawing    )
  ( M6DUB                     drawing    )
  ( M7DUB                     drawing    )
  ( M8DUB                     drawing    )
  ( PWH                       drawing    )
  ( NWH                       drawing    )
  ( M1R                       drawing    )
  ( M2R                       drawing    )
  ( M3R                       drawing    )
  ( M4R                       drawing    )
  ( M5R                       drawing    )
  ( M6R                       drawing    )
  ( M7R                       drawing    )
  ( M8R                       drawing    )
  ( M1SLOTB                   drawing    )
  ( M2SLOTB                   drawing    )
  ( M3SLOTB                   drawing    )
  ( M4SLOTB                   drawing    )
  ( M5SLOTB                   drawing    )
  ( M6SLOTB                   drawing    )
  ( M7SLOTB                   drawing    )
  ( M8SLOTB                   drawing    )
  ( NODMF                     drawing    )
  ( RODUMMY                   drawing    )
  ( RFDEV                     drawing    )
  ( RFMOSD                    drawing    )
  ( JVDUM                     drawing    )
  ( JVARDUM                   drawing    )
  ( HRPDMY                    drawing    )
  ( MIMDMY                    drawing    )
  ( INDMY                     drawing    )
  ( STIDMY                    drawing    )
 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )
  ( "0M"         drawing      "0m"             t t t t t )
  ( RGM          drawing      rgm              t t t t t )
  ( HT           drawing      ht               t t t t t )
  ( NEGR         drawing      negr             t t t t t )
  ( L0           drawing      l0               t t t t t )
  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        t t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      defaultPacket    t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )
  ( text         drawing      text             t t t t nil )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t nil nil nil nil )
  ( designFlow   drawing1     designFlow1      t nil nil nil nil )
  ( designFlow   drawing2     designFlow2      t nil nil nil nil )
  ( designFlow   drawing3     designFlow3      t nil nil nil nil )
  ( designFlow   drawing4     designFlow4      t nil nil nil nil )
  ( designFlow   drawing5     designFlow5      t nil nil nil nil )
  ( designFlow   drawing6     designFlow6      t nil nil nil nil )
  ( designFlow   drawing7     designFlow7      t nil nil nil nil )
  ( designFlow   drawing8     designFlow8      t nil nil nil nil )
  ( designFlow   drawing9     designFlow9      t nil nil nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t t t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t t t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( AA           drawing      aa               t t t t t )
  ( DUMAA        drawing      dumaa            t t t t t )
  ( NPAA         drawing      npaa             t t t t t )
  ( PPAA         drawing      ppaa             t t t t t )
  ( NW           drawing      nw               t t t t t )
  ( GT           drawing      gt               t t t t t )
  ( DUMGT        drawing      dumgt            t t t t t )
  ( DG           drawing      dg               t t t t t )
  ( HRP          drawing      hrp              t t t t t )
  ( SN           drawing      sn               t t t t t )
  ( SP           drawing      sp               t t t t t )
  ( SAB          drawing      sab              t t t t t )
  ( VSIA         drawing      vsia             t t t t t )
  ( CT           drawing      ct               t t t t t )
  ( M1           drawing      m1               t t t t t )
  ( M2           drawing      m2               t t t t t )
  ( M3           drawing      m3               t t t t t )
  ( M4           drawing      m4               t t t t t )
  ( M5           drawing      m5               t t t t t )
  ( M6           drawing      m6               t t t t t )
  ( M7           drawing      m7               t t t t t )
  ( M8           drawing      m8               t t t t t )
  ( V1           drawing      v1               t t t t t )
  ( V2           drawing      v2               t t t t t )
  ( V3           drawing      v3               t t t t t )
  ( V4           drawing      v4               t t t t t )
  ( V5           drawing      v5               t t t t t )
  ( V6           drawing      v6               t t t t t )
  ( V7           drawing      v7               t t t t t )
  ( PA           drawing      pa               t t t t t )
  ( M1TXT        drawing      m1txt            t t t t t )
  ( M2TXT        drawing      m2txt            t t t t t )
  ( M3TXT        drawing      m3txt            t t t t t )
  ( M4TXT        drawing      m4txt            t t t t t )
  ( M5TXT        drawing      m5txt            t t t t t )
  ( M6TXT        drawing      m6txt            t t t t t )
  ( M7TXT        drawing      m7txt            t t t t t )
  ( M8TXT        drawing      m8txt            t t t t t )
  ( NN           drawing      nn               t t t t t )
  ( RESNW       drawing      resnw           t t t t t )
  ( RESP1       drawing      resp1           t t t t t )
  ( RESAA       drawing      resaa           t t t t t )
  ( SUBD         drawing      subd             t t t t t )
  ( HTNWL        drawing      htnwl            t t t t t )
  ( EXCLU        drawing      exclu            t t t t t )
  ( ESDIO1       drawing      esdio1           t t t t t )
  ( POWRING      drawing      powring          t t t t t )
  ( ESDIO2       drawing      esdio2           t t t t t )
  ( DMPNP        drawing      dmpnp            t t t t t )
  ( CAPBP        drawing      capbp            t t t t t )
  ( DSTR         drawing      dstr             t t t t t )
  ( SURNW        drawing      surnw            t t t t t )
  ( AMO          drawing      amo              t t t t t )
  ( CO           drawing      co               t t t t t )
  ( BORDER       drawing      border           t t t t t )
  ( KV           drawing      kv               t t t t t )
  ( AR           drawing      ar               t t t t t )
  ( TP           drawing      tp               t t t t t )
  ( PC           drawing      pc               t t t t t )
  ( DP           drawing      dp               t t t t t )
  ( CL           drawing      cl               t t t t t )
  ( DNW          drawing      dnw              t t t t t )
  ( PW           drawing      pw               t t t t t )
  ( NC           drawing      nc               t t t t t )
  ( CPT          drawing      cpt              t t t t t )
  ( BNP          drawing      bnp              t t t t t )
  ( TN           drawing      tn               t t t t t )
  ( CODE         drawing      code             t t t t t )
  ( LOGO         drawing      logo             t t t t t )
  ( ONO          drawing      ono              t t t t t )
  ( BC           drawing      bc               t t t t t )
  ( P2           drawing      p2               t t t t t )
  ( P3           drawing      p3               t t t t t )
  ( P4           drawing      p4               t t t t t )
  ( HR           drawing      hr               t t t t t )
  ( NLL          drawing      nll              t t t t t )
  ( NLH          drawing      nlh              t t t t t )
  ( PLH          drawing      plh              t t t t t )
  ( PLL          drawing      pll              t t t t t )
  ( ESD1         drawing      esd1             t t t t t )
  ( ESD2         drawing      esd2             t t t t t )
  ( MVP          drawing      mvp              t t t t t )
  ( MVN          drawing      mvn              t t t t t )
  ( VTPH         drawing      vtph             t t t t t )
  ( VTNH         drawing      vtnh             t t t t t )
  ( IDT          drawing      idt              t t t t t )
  ( CM           drawing      cm               t t t t t )
  ( DDN          drawing      ddn              t t t t t )
  ( HVBN         drawing      hvbn             t t t t t )
  ( NDDD         drawing      nddd             t t t t t )
  ( DDP          drawing      ddp              t t t t t )
  ( MIM          drawing      mim              t t t t t )
  ( M0           drawing      m0               t t t t t )
  ( INST         drawing      inst             t t t t t )
  ( M1DUM        drawing      m1dum            t t t t t )
  ( M2DUM        drawing      m2dum            t t t t t )
  ( M3DUM        drawing      m3dum            t t t t t )
  ( M4DUM        drawing      m4dum            t t t t t )
  ( M5DUM        drawing      m5dum            t t t t t )
  ( M6DUM        drawing      m6dum            t t t t t )
  ( M7DUM        drawing      m7dum            t t t t t )
  ( M8DUM        drawing      m8dum            t t t t t )
  ( M1SLOT       drawing      m1slot           t t t t t )
  ( M2SLOT       drawing      m2slot           t t t t t )
  ( M3SLOT       drawing      m3slot           t t t t t )
  ( M4SLOT       drawing      m4slot           t t t t t )
  ( M5SLOT       drawing      m5slot           t t t t t )
  ( M6SLOT       drawing      m6slot           t t t t t )
  ( M7SLOT       drawing      m7slot           t t t t t )
  ( M8SLOT       drawing      m8slot           t t t t t )
  ( PIPR         drawing      pipr             t t t t t )
  ( FUSE         drawing      fuse             t t t t t )
  ( PI           drawing      pi               t t t t t )
  ( ALPA         drawing      alpa             t t t t t )
  ( TTXT         drawing      ttxt             t t t t t )
  ( BTXT         drawing      btxt             t t t t t )
  ( CTXT         drawing      ctxt             t t t t t )
  ( DUMBM        drawing      dumbm            t t t t t )
  ( DUMBA        drawing      dumba            t t t t t )
  ( DUMBP        drawing      dumbp            t t t t t )
  ( VARMOS      drawing      varmos          t t t t t )
  ( VARJUN     drawing      varjun         t t t t t )
  ( PFL          drawing      pfl              t t t t t )
  ( SDOP         drawing      sdop             t t t t t )
  ( OPCBA        drawing      opcba            t t t t t )
  ( OPCBP        drawing      opcbp            t t t t t )
  ( OPCBM        drawing      opcbm            t t t t t )
  ( NDRF         drawing      ndrf             t t t t t )
  ( PDRF         drawing      pdrf             t t t t t )
  ( PPCI         drawing      ppci             t t t t t )
  ( NPCI         drawing      npci             t t t t t )
  ( PWHT         drawing      pwht             t t t t t )
  ( NWHT         drawing      nwht             t t t t t )
  ( PIP          drawing      pip              t t t t t )
  ( NLHT         drawing      nlht             t t t t t )
  ( PLHT         drawing      plht             t t t t t )
  ( ESD5V        drawing      esd5v            t t t t t )
  ( TG           drawing      tg               t t t t t )
  ( PDC          drawing      pdc              t t t t t )
  ( PWL          drawing      pwl              t t t t t )
  ( DCTY         drawing      dcty             t t t t t )
  ( SBT          drawing      sbt              t t t t t )
  ( SUBTXT       drawing      subtxt           t t t t t )
  ( WELTXT       drawing      weltxt           t t t t t )
  ( DIFTXT       drawing      diftxt           t t t t t )
  ( POLYTXT      drawing      polytxt          t t t t t )
  ( M1B          drawing      m1b              t t t t t )
  ( M2B          drawing      m2b              t t t t t )
  ( M3B          drawing      m3b              t t t t t )
  ( M4B          drawing      m4b              t t t t t )
  ( M5B          drawing      m5b              t t t t t )
  ( M6B          drawing      m6b              t t t t t )
  ( M7B          drawing      m7b              t t t t t )
  ( M8B          drawing      m8b              t t t t t )
  ( M1DUB        drawing      m1dub            t t t t t )
  ( M2DUB        drawing      m2dub            t t t t t )
  ( M3DUB        drawing      m3dub            t t t t t )
  ( M4DUB        drawing      m4dub            t t t t t )
  ( M5DUB        drawing      m5dub            t t t t t )
  ( M6DUB        drawing      m6dub            t t t t t )
  ( M7DUB        drawing      m7dub            t t t t t )
  ( M8DUB        drawing      m8dub            t t t t t )
  ( PWH          drawing      pwh              t t t t t )
  ( NWH          drawing      nwh              t t t t t )
  ( M1R          drawing      m1r              t t t t t )
  ( M2R          drawing      m2r              t t t t t )
  ( M3R          drawing      m3r              t t t t t )
  ( M4R          drawing      m4r              t t t t t )
  ( M5R          drawing      m5r              t t t t t )
  ( M6R          drawing      m6r              t t t t t )
  ( M7R          drawing      m7r              t t t t t )
  ( M8R          drawing      m8r              t t t t t )
  ( M1SLOTB      drawing      m1slotb          t t t t t )
  ( M2SLOTB      drawing      m2slotb          t t t t t )
  ( M3SLOTB      drawing      m3slotb          t t t t t )
  ( M4SLOTB      drawing      m4slotb          t t t t t )
  ( M5SLOTB      drawing      m5slotb          t t t t t )
  ( M6SLOTB      drawing      m6slotb          t t t t t )
  ( M7SLOTB      drawing      m7slotb          t t t t t )
  ( M8SLOTB      drawing      m8slotb          t t t t t )
  ( NODMF        drawing      nodmf            t t t t t )
  ( RODUMMY      drawing      rodummy          t t t t t )
  ( RFDEV        drawing      rfdev            t t t t t )
  ( RFMOSD       drawing      rfmosd           t t t t t )
  ( JVDUM        drawing      jvdum            t t t t t )
  ( JVARDUM      drawing      jvardum          t t t t t )
  ( HRPDMY       drawing      hrpdmy           t t t t t )
  ( MIMDMY       drawing      mimdmy           t t t t t )
  ( INDMY        drawing      indmy            t t t t t )
  ( STIDMY       drawing      stidmy           t t t t t )
 ) ;techDisplays

techLayerProperties(
;( PropName               Layer1 [ Layer2 ]            PropValue )
)

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 viaLayers(
 ;( layer1      viaLayer        layer2     )
 ;( ------      --------        ------     )
  ( ("GT" "drawing")	("CT" "drawing")	("M1" "drawing")	 )
  ( ("M1" "drawing")	("V1" "drawing")	("M2" "drawing")	 )
  ( ("M2" "drawing")	("V2" "drawing")	("M3" "drawing")	 )
  ( ("M3" "drawing")	("V3" "drawing")	("M4" "drawing")	 )
  ( ("M4" "drawing")	("V4" "drawing")	("M5" "drawing")	 )
  ( ("M5" "drawing")	("V5" "drawing")	("M6" "drawing")	 )
  ( ("M6" "drawing")	("V6" "drawing")	("M7" "drawing")	 )
  ( ("M7" "drawing")	("V7" "drawing")	("M8" "drawing")	 )
 ) ;viaLayers

 streamLayers(
 ;( layer       streamNumber    dataType        translate )
 ;( -----       ------------    --------        --------- )
  ( ("AMO" "drawing")	7         	0       	t	 )
  ( ("CO" "drawing")	8         	0       	t	 )
  ( ("KV" "drawing")	9         	0       	t	 )
  ( ("AA" "drawing")	10        	0       	t	 )
  ( ("AR" "drawing")	11        	0       	t	 )
  ( ("NPAA" "drawing")	12        	0       	t	 )
  ( ("PPAA" "drawing")	13        	0       	t	 )
  ( ("NW" "drawing")	14        	0       	t	 )
  ( ("TP" "drawing")	15        	0       	t	 )
  ( ("PC" "drawing")	16        	0       	t	 )
  ( ("DP" "drawing")	17        	0       	t	 )
  ( ("CL" "drawing")	18        	0       	t	 )
  ( ("DNW" "drawing")	19        	0       	t	 )
  ( ("PW" "drawing")	20        	0       	t	 )
  ( ("NC" "drawing")	21        	0       	t	 )
  ( ("CPT" "drawing")	22        	0       	t	 )
  ( ("BNP" "drawing")	23        	0       	t	 )
  ( ("TN" "drawing")	24        	0       	t	 )
  ( ("CODE" "drawing")	25        	0       	t	 )
  ( ("LOGO" "drawing")	26        	0       	t	 )
  ( ("BC" "drawing")	28        	0       	t	 )
  ( ("DG" "drawing")	29        	0       	t	 )
  ( ("GT" "drawing")	30        	0       	t	 )
  ( ("P2" "drawing")	31        	0       	t	 )
  ( ("P3" "drawing")	32        	0       	t	 )
  ( ("P4" "drawing")	33        	0       	t	 )
  ( ("HR" "drawing")	34        	0       	t	 )
  ( ("NLL" "drawing")	35        	0       	t	 )
  ( ("NLH" "drawing")	36        	0       	t	 )
  ( ("PLH" "drawing")	37        	0       	t	 )
  ( ("PLL" "drawing")	38        	0       	t	 )
  ( ("HRP" "drawing")	39        	0       	t	 )
  ( ("SN" "drawing")	40        	0       	t	 )
  ( ("ESD1" "drawing")	41        	0       	t	 )
  ( ("ESD2" "drawing")	42        	0       	t	 )
  ( ("SP" "drawing")	43        	0       	t	 )
  ( ("MVP" "drawing")	44        	0       	t	 )
  ( ("MVN" "drawing")	45        	0       	t	 )
  ( ("VTPH" "drawing")	46        	0       	t	 )
  ( ("VTNH" "drawing")	47        	0       	t	 )
  ( ("SAB" "drawing")	48        	0       	t	 )
  ( ("IDT" "drawing")	49        	0       	t	 )
  ( ("CT" "drawing")	50        	0       	t	 )
  ( ("CM" "drawing")	51        	0       	t	 )
  ( ("DDN" "drawing")	53        	0       	t	 )
  ( ("HVBN" "drawing")	54        	0       	t	 )
  ( ("NDDD" "drawing")	55        	0       	t	 )
  ( ("DDP" "drawing")	56        	0       	t	 )
  ( ("MIM" "drawing")	58        	0       	t	 )
  ( ("M0" "drawing")	59        	0       	t	 )
  ( ("M1" "drawing")	61        	0       	t	 )
  ( ("M2" "drawing")	62        	0       	t	 )
  ( ("M3" "drawing")	63        	0       	t	 )
  ( ("M4" "drawing")	64        	0       	t	 )
  ( ("M5" "drawing")	65        	0       	t	 )
  ( ("M6" "drawing")	66        	0       	t	 )
  ( ("M7" "drawing")	67        	0       	t	 )
  ( ("M8" "drawing")	68        	0       	t	 )
  ( ("V1" "drawing")	70        	0       	t	 )
  ( ("V2" "drawing")	71        	0       	t	 )
  ( ("V3" "drawing")	72        	0       	t	 )
  ( ("V4" "drawing")	73        	0       	t	 )
  ( ("V5" "drawing")	74        	0       	t	 )
  ( ("V6" "drawing")	75        	0       	t	 )
  ( ("V7" "drawing")	76        	0       	t	 )
  ( ("PIPR" "drawing")	79        	0       	t	 )
  ( ("PA" "drawing")	80        	0       	t	 )
  ( ("FUSE" "drawing")	81        	0       	t	 )
  ( ("PI" "drawing")	82        	0       	t	 )
  ( ("ALPA" "drawing")	83        	0       	t	 )
  ( ("NN" "drawing")	85        	0       	t	 )
  ( ("VSIA" "drawing")	63        	63      	t	 )
  ( ("TTXT" "drawing")	87        	0       	t	 )
  ( ("BTXT" "drawing")	88        	0       	t	 )
  ( ("CTXT" "drawing")	89        	0       	t	 )
  ( ("DUMBP" "drawing")	92        	0       	t	 )
  ( ("VARMOS" "drawing")	93        	0       	t	 )
  ( ("VARJUN" "drawing")	94        	0       	t	 )
  ( ("RESNW" "drawing")	95        	0       	t	 )
  ( ("RESP1" "drawing")	96        	0       	t	 )
  ( ("RESAA" "drawing")	97        	0       	t	 )
  ( ("OPCBA" "drawing")	100       	0       	t	 )
  ( ("OPCBP" "drawing")	101       	0       	t	 )
  ( ("OPCBM" "drawing")	102       	0       	t	 )
  ( ("PWH" "drawing")	105       	0       	t	 )
  ( ("NWH" "drawing")	106       	0       	t	 )
  ( ("BORDER" "drawing")	127       	0       	t	 )
  ( ("HTNWL" "drawing")	131       	0       	t	 )
  ( ("SUBD" "drawing")	131       	1       	t	 )
  ( ("EXCLU" "drawing")	132       	0       	t	 )
  ( ("ESDIO1" "drawing")	133       	0       	t	 )
  ( ("ESD5V" "drawing")         133             1               t        )
  ( ("POWRING" "drawing")       133             2               t        )
  ( ("ESDIO2" "drawing")        133             3               t        )
  ( ("DMPNP" "drawing")	134       	0       	t	 )
  ( ("PDC" "drawing")	135       	0       	t	 )
  ( ("PWL" "drawing")	136       	0       	t	 )
  ( ("CAPBP" "drawing")	137       	0       	t	 )
  ( ("DSTR" "drawing")	138       	0       	t	 )
  ( ("DCTY" "drawing")	139       	0       	t	 )
  ( ("M1TXT" "drawing")	141       	0       	t	 )
  ( ("M2TXT" "drawing")	142       	0       	t	 )
  ( ("M3TXT" "drawing")	143       	0       	t	 )
  ( ("M4TXT" "drawing")	144       	0       	t	 )
  ( ("M5TXT" "drawing")	145       	0       	t	 )
  ( ("M6TXT" "drawing")	146       	0       	t	 )
  ( ("M7TXT" "drawing")	147       	0       	t	 )
  ( ("M8TXT" "drawing")	148       	0       	t	 )
  ( ("SUBTXT" "drawing")	161       	0       	t	 )
  ( ("WELTXT" "drawing")	162       	0       	t	 )
  ( ("DIFTXT" "drawing")	163       	0       	t	 )
  ( ("POLYTXT" "drawing")	164       	0       	t	 )
  ( ("M1B" "drawing")	151       	0       	t	 )
  ( ("M2B" "drawing")	152       	0       	t	 )
  ( ("M3B" "drawing")	153       	0       	t	 )
  ( ("M4B" "drawing")	154       	0       	t	 )
  ( ("M5B" "drawing")	155       	0       	t	 )
  ( ("M6B" "drawing")	156       	0       	t	 )
  ( ("M7B" "drawing")	157       	0       	t	 )
  ( ("M8B" "drawing")	158       	0       	t	 )
  ( ("M1R" "drawing")	171       	0       	t	 )
  ( ("M2R" "drawing")	172       	0       	t	 )
  ( ("M3R" "drawing")	173       	0       	t	 )
  ( ("M4R" "drawing")	174       	0       	t	 )
  ( ("M5R" "drawing")	175       	0       	t	 )
  ( ("M6R" "drawing")	176       	0       	t	 )
  ( ("M7R" "drawing")	177       	0       	t	 )
  ( ("M8R" "drawing")	178       	0       	t	 )
  ( ("HRPDMY" "drawing")	210       	0       	t	 )
  ( ("DUMBM" "drawing")	90        	0       	t	 )
  ( ("RODUMMY" "drawing")	199       	0       	t	 )
  ( ("DUMBA" "drawing")	91        	0       	t	 )
  ( ("M2DUM" "drawing")	62        	1       	t	 )
  ( ("M1DUM" "drawing")	61        	1       	t	 )
  ( ("M1SLOT" "drawing")	61        	2       	t	 )
  ( ("M2SLOT" "drawing")	62        	2       	t	 )
  ( ("M3DUM" "drawing")	63        	1       	t	 )
  ( ("M3SLOT" "drawing")	63        	2       	t	 )
  ( ("M4DUM" "drawing")	64        	1       	t	 )
  ( ("M4SLOT" "drawing")	64        	2       	t	 )
  ( ("M5DUM" "drawing")	65        	1       	t	 )
  ( ("M5SLOT" "drawing")	65        	2       	t	 )
  ( ("INST" "drawing")	60        	0       	t	 )
  ( ("M6SLOT" "drawing")	66        	2       	t	 )
  ( ("M7DUM" "drawing")	67        	1       	t	 )
  ( ("M7SLOT" "drawing")	67        	2       	t	 )
  ( ("PIP" "drawing")	113       	0       	t	 )
  ( ("M6DUM" "drawing")	66        	1       	t	 )
  ( ("M8DUM" "drawing")	68        	1       	t	 )
  ( ("M8SLOT" "drawing")	68        	2       	t	 )
  ( ("SBT" "drawing")	140       	0       	t	 )
  ( ("M1DUB" "drawing")	151       	1       	t	 )
  ( ("M2DUB" "drawing")	152       	1       	t	 )
  ( ("M3DUB" "drawing")	153       	1       	t	 )
  ( ("M4DUB" "drawing")	154       	1       	t	 )
  ( ("M5DUB" "drawing")	155       	1       	t	 )
  ( ("M6DUB" "drawing")	156       	1       	t	 )
  ( ("M7DUB" "drawing")	157       	1       	t	 )
  ( ("PPCI" "drawing")	107       	0       	t	 )
  ( ("NPCI" "drawing")	108       	0       	t	 )
  ( ("M8DUB" "drawing")	158       	1       	t	 )
  ( ("M1SLOTB" "drawing")	171       	1       	t	 )
  ( ("M2SLOTB" "drawing")	172       	1       	t	 )
  ( ("M3SLOTB" "drawing")	173       	1       	t	 )
  ( ("M4SLOTB" "drawing")	174       	1       	t	 )
  ( ("M5SLOTB" "drawing")	175       	1       	t	 )
  ( ("M6SLOTB" "drawing")	176       	1       	t	 )
  ( ("M7SLOTB" "drawing")	177       	1       	t	 )
  ( ("M8SLOTB" "drawing")	178       	1       	t	 )
  ( ("NODMF" "drawing")	180       	0       	t	 )
  ( ("RFDEV" "drawing")	181       	0       	t	 )
  ( ("RFMOSD" "drawing")	182       	0       	t	 )
  ( ("JVARDUM" "drawing")	183       	0       	t	 )
  ( ("JVDUM" "drawing") 188             0               t        )
  ( ("MIMDMY" "drawing")	211       	0       	t	 )
  ( ("INDMY" "drawing")	212       	0       	t	 )
  ( ("ONO" "drawing")	27        	0       	t	 )
  ( ("NLHT" "drawing")	114       	0       	t	 )
  ( ("PLHT" "drawing")	115       	0       	t	 )
  ( ("TG" "drawing")	125       	0       	t	 )
  ( ("PFL" "drawing")	98        	0       	t	 )
  ( ("SURNW" "drawing")	95        	1       	t	 )
  ( ("STIDMY" "drawing")	215       	0       	t	 )
  ( ("SDOP" "drawing")	99        	0       	t	 )
  ( ("NDRF" "drawing")	103       	0       	t	 )
  ( ("PDRF" "drawing")	104       	0       	t	 )
  ( ("PWHT" "drawing")	109       	0       	t	 )
  ( ("NWHT" "drawing")	110       	0       	t	 )
  ( ("L0" "drawing")	0         	0       	t	 )
  ( ("0M" "drawing")	1         	0       	t	 )
  ( ("RGM" "drawing")	2         	0       	t	 )
  ( ("HT" "drawing")	3         	0       	t	 )
  ( ("NEGR" "drawing")	4         	0       	t	 )
  ( ("DUMAA" "drawing")	10        	1       	t	 )
  ( ("DUMGT" "drawing")	30        	1       	t	 )
 ) ;streamLayers

) ;layerRules


;********************************
; PHYSICAL RULES
;********************************
physicalRules(

 mfgGridResolution(
      ( 0.001000 )
 ) ;mfgGridResolution

) ;physicalRules
